### PR TITLE
add redux-diff-logger functionally, fix theaqua/redux-logger#136

### PR DESCRIPTION
**Pull request by sibeliusseraphini**

### CODE REVIEW

**Comment by toxickg** [comment]
We can merge it for now. It works.

I think that we should also add an option that enables conditional diffing (`diffPredicate`). What do you think?

**Comment by toxickg** [comment]
I've just added [`diffPredicate` option](https://github.com/toxickg/redux-logger/commit/f26f9251d95d33a8dac2b3095be1459167668fd1). I'll make a pull request as we agree to merge this one.

**Comment by sibeliusseraphini** [comment]
@toxickg great

**Comment by toxickg** [comment]
I merged it and also added description of diff feature.

**Pull request merged**
