### PR TITLE
chore: upgrade deps, fix eslint and lint errors, change to eslint-con…

### PR DESCRIPTION
**Pull request by sibeliusseraphini**
…fig-airbnb

### CODE REVIEW

**Comment by theaqua** [comment]
Well done, let's go through it. Remove airbnb config, dtrussia's is mine and we'll use it.

Let's discuss about diff library. We already have several options from https://github.com/fcomb/redux-diff-logger/issues/1, what do you think about them?

**Comment by sibeliusseraphini** [comment]
https://github.com/jqestate/eslint-config-dtrussia works fine with eslint 2.9?

https://github.com/fcomb/redux-diff-logger/issues/1 - I think we can move the current implementation to this package and move this issue here,so we can join the efforts

It is easy to use jsondiffpatch, but we need to create our custom formatter for it

**Comment by sibeliusseraphini** [comment]
any reason of not use the community build eslint-config-airbnb?

**Comment by theaqua** [comment]
We don't need it. We have several differences from it for my own taste.
I'll update eslint to 2.9 on the weekend.

We'll release diff feature as we finished it, so let's do it in this PR.

**Comment by sibeliusseraphini** [comment]
ok, just let me know when then I will update this PR

**Comment by sibeliusseraphini** [comment]
any progress on https://github.com/jqestate/eslint-config-dtrussia?

**Comment by theaqua** [comment]
@sibeliusseraphini released 2.2.1

**Comment by sibeliusseraphini** [comment]
I think I will give up of this PR, why are you using eslint-config-airbnb at redux-diff-logger (https://github.com/fcomb/redux-diff-logger/blob/master/.eslintrc) and you want to use your own style with redux-logger

You are looking for a new maintainer (https://github.com/theaqua/redux-logger/issues/148) but you are more worried about the style instead of the code.

I have 41 problems (40 errors, 1 warning) using your style against 0 using eslint-config-airbnb

```js
redux-logger/src/diff.js
   5:3   error  Identifier name 'E' is too short. (< 2)                 id-length
   6:12  error  Strings must use backtick                               quotes
   7:11  error  Strings must use backtick                               quotes
   9:3   error  Identifier name 'N' is too short. (< 2)                 id-length
  10:12  error  Strings must use backtick                               quotes
  11:11  error  Strings must use backtick                               quotes
  13:3   error  Identifier name 'D' is too short. (< 2)                 id-length
  14:12  error  Strings must use backtick                               quotes
  15:11  error  Strings must use backtick                               quotes
  17:3   error  Identifier name 'A' is too short. (< 2)                 id-length
  18:12  error  Strings must use backtick                               quotes
  19:11  error  Strings must use backtick                               quotes
  31:3   error  Expected indentation of 4 space characters but found 2  indent
  31:8   error  Strings must use backtick                               quotes
  32:5   error  Expected indentation of 6 space characters but found 4  indent
  32:25  error  Strings must use backtick                               quotes
  33:3   error  Expected indentation of 4 space characters but found 2  indent
  33:8   error  Strings must use backtick                               quotes
  34:5   error  Expected indentation of 6 space characters but found 4  indent
  34:25  error  Strings must use backtick                               quotes
  35:3   error  Expected indentation of 4 space characters but found 2  indent
  35:8   error  Strings must use backtick                               quotes
  36:5   error  Expected indentation of 6 space characters but found 4  indent
  36:25  error  Strings must use backtick                               quotes
  37:3   error  Expected indentation of 4 space characters but found 2  indent
  37:8   error  Strings must use backtick                               quotes
  38:5   error  Expected indentation of 6 space characters but found 4  indent
  38:26  error  Strings must use backtick                               quotes
  39:3   error  Expected indentation of 4 space characters but found 2  indent
  40:5   error  Expected indentation of 6 space characters but found 4  indent
  49:29  error  Strings must use backtick                               quotes
  51:20  error  Strings must use backtick                               quotes
  54:16  error  Strings must use backtick                               quotes
  65:16  error  Strings must use backtick                               quotes

redux-logger/src/index.js
  25:3  error    Expected indentation of 4 space characters but found 2  indent
  26:5  error    Expected indentation of 6 space characters but found 4  indent
  27:3  error    Expected indentation of 4 space characters but found 2  indent
  28:5  error    Expected indentation of 6 space characters but found 4  indent
  29:3  error    Expected indentation of 4 space characters but found 2  indent
  30:5  error    Expected indentation of 6 space characters but found 4  indent
  82:5  warning  Unexpected console statement                            no-console
```

**Comment by theaqua** [comment]
I don't give a single fuck about style, I have a config which I use in all my projects. 

I'll merge #152 as update of dependencies. Please, continue implementing diff feature in this PR.

**Comment by sibeliusseraphini** [comment]
closing this in favor of https://github.com/theaqua/redux-logger/pull/153

**Pull request closed without merging**
